import type { ComponentType } from 'react';
import { doAction } from '@artisanpack-ui/hooks-js';

/**
 * Runtime loader for plugin-supplied React pages shipped as Module Federation
 * remotes. The Inertia resolver in {@see resources/js/app.tsx} consults the
 * federated-module manifest shared by `HandleInertiaRequests`, and when a
 * requested page name matches, delegates to {@link loadFederatedPage} to
 * fetch and hydrate the remote bundle.
 *
 * Remotes are DYNAMIC — plugin bundles are registered at load time (rather
 * than baked into the Vite build). The `@originjs/vite-plugin-federation`
 * runtime is imported via the `virtual:__federation__` module the host
 * build emits.
 */

/**
 * Shape of a manifest entry the host shares as an Inertia prop for each
 * plugin-provided page.
 */
export type FederatedModuleEntry = {
    /** The remote name registered by the plugin (e.g. `hello-world`). */
    remote: string;
    /** Absolute URL of the plugin's `remoteEntry.js` bundle. */
    entry: string;
    /** The exposed module identifier inside the remote (e.g. `./dashboard`). */
    module: string;
};

/** Page-keyed lookup consumed by the Inertia resolver. */
export type FederatedPageManifest = Record<string, FederatedModuleEntry>;

/**
 * The full federated-module manifest the server shares as an Inertia prop.
 * `pages` powers page resolution; `bootModules` is preloaded before the
 * first admin page mounts so plugin-registered actions/filters bind before
 * the shell reads them.
 */
export type FederatedModuleManifest = {
    pages: FederatedPageManifest;
    bootModules: FederatedModuleEntry[];
};

type FederationRuntime = {
    __federation_method_setRemote: (
        name: string,
        config: {
            url: string | (() => Promise<string>);
            format: 'esm' | 'systemjs' | 'var';
            from: 'vite' | 'webpack';
        },
    ) => void;
    __federation_method_getRemote: (name: string, module: string) => Promise<unknown>;
};

/** Cache of `(remote, module)` → loaded page component so navigations reuse the remote. */
const pageCache = new Map<string, Promise<{ default: ComponentType<Record<string, unknown>> }>>();

/** Remotes that have already been registered with the federation runtime. */
const registeredRemotes = new Map<string, string>();

/**
 * Import the federation runtime the host build emits.
 *
 * `virtual:__federation__` is generated by `@originjs/vite-plugin-federation`
 * at build time; TypeScript can't resolve the module id, so the import is
 * typed by a hand-written declaration and any resolution error is normalised
 * into a `PluginPageLoadError` so callers get a stable failure type instead
 * of a raw ESM module-resolution string.
 */
async function loadFederationRuntime(): Promise<FederationRuntime> {
    try {
        const runtime = (await import(/* @vite-ignore */ 'virtual:__federation__')) as FederationRuntime;
        return runtime;
    } catch (error) {
        throw new PluginPageLoadError(
            'Module Federation runtime is unavailable. Rebuild the host with `npm run build`.',
            { cause: error },
        );
    }
}

/**
 * Register `entry` with the federation runtime if we haven't yet — or if the
 * plugin swapped its entry URL between navigations. On a URL swap we drop
 * stale page-cache entries for the same remote so the next load actually
 * fetches the new bundle.
 *
 * IMPORTANT: this function is called synchronously (up to its first `await`)
 * inside {@link loadFederatedPage}'s promise-construction path, so all cache
 * mutation happens BEFORE the caller writes the new promise into
 * `pageCache`. If invalidation ran after `pageCache.set`, the just-inserted
 * entry would be wiped on the same navigation that populated it.
 */
async function ensureRemoteRegistered(entry: FederatedModuleEntry): Promise<FederationRuntime> {
    const previous = registeredRemotes.get(entry.remote);
    if (previous !== entry.entry) {
        for (const key of Array.from(pageCache.keys())) {
            if (key.startsWith(`${entry.remote}::`)) {
                pageCache.delete(key);
            }
        }
    }

    const runtime = await loadFederationRuntime();

    if (previous !== entry.entry) {
        runtime.__federation_method_setRemote(entry.remote, {
            url: entry.entry,
            format: 'esm',
            from: 'vite',
        });
        // Record only after the runtime call succeeds — a transient
        // `loadFederationRuntime()` failure could otherwise leave a
        // half-committed registration where the next retry sees the URL
        // as active and skips `setRemote`, failing again against a fresh
        // runtime that has no remote configured.
        registeredRemotes.set(entry.remote, entry.entry);
    }

    return runtime;
}

/**
 * Load a plugin-supplied Inertia page as a `{ default: Component }` module,
 * matching the shape Inertia's `resolve` callback returns from
 * `import.meta.glob`. Results are cached per `(remote, module, entry)` so
 * navigating away and back doesn't re-fetch the plugin bundle, and two
 * callers that ask for the same remote+module via different entry URLs
 * (rebuild hash swap, page and panel disagreeing on the manifest) each
 * get their own cache slot instead of stomping on each other.
 *
 * @throws PluginPageLoadError when the runtime, remote, or module fetch fails.
 */
export async function loadFederatedPage(
    entry: FederatedModuleEntry,
): Promise<{ default: ComponentType<Record<string, unknown>> }> {
    const cacheKey = `${entry.remote}::${entry.module}::${entry.entry}`;
    const cached   = pageCache.get(cacheKey);
    if (cached) {
        return cached;
    }

    const promise = (async () => {
        const runtime = await ensureRemoteRegistered(entry);

        let module: unknown;
        try {
            module = await runtime.__federation_method_getRemote(entry.remote, entry.module);
        } catch (error) {
            throw new PluginPageLoadError(
                `Failed to load plugin page \`${entry.module}\` from remote \`${entry.remote}\`.`,
                { cause: error },
            );
        }

        return normalisePageModule(module);
    })();

    pageCache.set(cacheKey, promise);
    // On rejection, evict so a retry (user navigation, StrictMode double-
    // invoke) can re-attempt instead of returning the failed promise for
    // the rest of the session.
    promise.catch(() => {
        if (pageCache.get(cacheKey) === promise) {
            pageCache.delete(cacheKey);
        }
    });

    return promise;
}

/**
 * Normalise however the plugin exported its component into the
 * `{ default: Component }` shape Inertia expects. Federation ESM output
 * yields `{ default: Component }`; a plugin that wraps that in another
 * default (e.g. re-export via a CJS interop shim) surfaces as
 * `{ default: { default: Component } }` — unwrap once more so both shapes
 * work.
 */
function normalisePageModule(module: unknown): {
    default: ComponentType<Record<string, unknown>>;
} {
    if (module && typeof module === 'object' && 'default' in module) {
        const value = (module as { default: unknown }).default;
        const inner =
            value && typeof value === 'object' && 'default' in value
                ? (value as { default: unknown }).default
                : value;

        if ('function' === typeof inner) {
            return { default: inner as ComponentType<Record<string, unknown>> };
        }
    }

    throw new PluginPageLoadError(
        'Plugin page module did not export a React component as its default export.',
    );
}

/**
 * Preload every plugin's `bootModule` (from the shared federated-modules
 * manifest) so the boot modules' top-level side effects — typically
 * `addAction` / `addFilter` calls that bind plugin hooks against the
 * host's shared `@artisanpack-ui/hooks-js` singleton — run BEFORE the
 * admin shell mounts its first page and calls `applyFilters`. Without
 * this preload, a plugin's `keystone.admin.navGroups` filter callback
 * would attach after the sidebar has already computed its groups, so
 * the plugin's nav additions wouldn't appear until the next render.
 *
 * Failures are isolated per boot module: we `console.warn` and keep
 * going so a single broken plugin can't block the admin shell from
 * mounting. The federation runtime handles remote registration
 * internally via {@link ensureRemoteRegistered}, and this function
 * intentionally awaits each `__federation_method_getRemote` call so
 * the side effects have committed by the time the promise resolves.
 *
 * Idempotent — boot modules share the same page cache, so a second call
 * with the same entries is essentially a no-op.
 */
export async function preloadFederatedBootModules(
    entries: readonly FederatedModuleEntry[],
): Promise<void> {
    if (0 === entries.length) {
        return;
    }

    await Promise.all(
        entries.map(async (entry) => {
            try {
                const runtime = await ensureRemoteRegistered(entry);
                await runtime.__federation_method_getRemote(entry.remote, entry.module);
            } catch (error) {
                console.warn(
                    `[keystone] Failed to preload boot module \`${entry.module}\` from plugin \`${entry.remote}\`.`,
                    error,
                );
                // Broadcast to `keystone.admin.error.boundary` so error-
                // tracking plugins (Sentry, Bugsnag) can pick up preload
                // failures — the console warning alone gives no signal to
                // the shell that a plugin failed to bind its filters.
                // Scope `bootModule` distinguishes these from render-time
                // plugin/panel boundary failures.
                doAction('keystone.admin.error.boundary', {
                    scope: 'bootModule',
                    error: error instanceof Error ? error : new Error(String(error)),
                    pluginName: entry.remote,
                    module:     entry.module,
                });
            }
        }),
    );
}

export class PluginPageLoadError extends Error {
    constructor(message: string, options?: ErrorOptions) {
        super(message, options);
        this.name = 'PluginPageLoadError';
    }
}
